language: java
jdk:
  - openjdk8

####################################################################################################
#                                         Setup Databases                                          #
#                          https://docs.travis-ci.com/user/database-setup                          #
####################################################################################################
services:
  - mysql

mysql:
  database: test1
  username: root
  encoding: utf8

#before_script:
 # - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_install:
  - chmod a+x gradlew
  - - ls -al /etc/mysql
    - sudo service mysql stop
    - echo "[mysqld]" > $HOME/.my.cnf
    - echo "lower-case-table-names = 1" >> $HOME/.my.cnf
    - cat $HOME/.my.cnf # be sure it registered
    - service --status-all
    - sudo sed -i '/\[mysqld\]/a lower_case_table_names = 1 '  /etc/mysql/mysql.conf.d/mysqld.cnf
    - cat /etc/mysql/my.cnf
    - sudo service mysql start
    - mysql --verbose -e  "show variables like 'lower%';" --user=root
    - mysql -u root --password="" < ./create_tables.sql

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jghgahee12@gmail.com