language: java
jdk:
  - openjdk8

services:
  - mysql

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod a+x gradlew
  #- mysql -e 'CREATE DATABASE test;'
  #- mysql -u root -e 'CREATE DATABASE test;'
  #- mysql -u root
  #- mysql -e 'CREATE DATABASE test;'


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jghgahee12@gmail.com