language: java
jdk:
  - openjdk8

####################################################################################################
#                                         Setup Databases                                          #
#                          https://docs.travis-ci.com/user/database-setup                          #
####################################################################################################
services:
  - mysql

before_install:
  - chmod a+x gradlew
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jghgahee12@gmail.com