version: "3.0"
services:
  #service명
  mysql:
    image: mysql:8
    # 컨테이너 이름 설정(해도되고 안해도 되고)
    container_name: matzip_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
    ports:
      - 3307:3306


  matzip_app:
    container_name: matzip_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ADDRESS: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8088:8080
    restart: on-failure
    links:
      - mysql
    depends_on:
      - mysql